test_that("base URL, key lookup, and options are documented", {
  expect_equal(grant_base_url(), "https://api.simpler.grants.gov")

  withr::local_envvar(GRANTS_GOV_API_KEY = "test-key")
  expect_equal(grant_api_key(), "test-key")
  expect_equal(grant_api_key(required = FALSE), "test-key")

  withr::local_envvar(GRANTS_GOV_API_KEY = NA)
  expect_null(grant_api_key(required = FALSE))
  expect_error(grant_api_key(), "GRANTS_GOV_API_KEY")

  endpoints <- grant_endpoints()
  expect_equal(endpoints$authentication$header, "X-API-Key")
  expect_equal(endpoints$endpoints$search_opportunities$path, "/v1/opportunities/search")
  expect_equal(endpoints$endpoints$search_agencies$path, "/v1/agencies/search")
  expect_equal(endpoints$endpoints$get_opportunity$method, "GET")
  expect_equal(endpoints$endpoints$get_opportunity_legacy$function_name, "grant_get_opportunity_legacy")
  expect_equal(endpoints$endpoints$list_extracts$function_name, "grant_list_extracts")
  expect_equal(endpoints$endpoints$common_grants$get_opportunity$path, "/common-grants/opportunities/{oppId}")
  expect_equal(endpoints$endpoints$organizations$list_users$function_name, "grant_list_organization_users")
  expect_equal(endpoints$endpoints$health$path, "/health")
  expect_equal(endpoints$endpoints$health$function_name, "grant_health")
  expect_true("opportunity_status" %in% endpoints$search$filters)
  expect_true("opportunities_json" %in% endpoints$extracts$extract_type)
  expect_true("retry-after" %in% endpoints$rate_limit_headers)

  expect_true("OR" %in% grant_search_options()$query_operator)
  expect_true("created_at" %in% grant_extract_options()$filters)
  expect_true("x-ratelimit-remaining" %in% grant_rate_limit_headers())
})
